project:
  type: book
  output-dir: _book
book:
  title: "Practical Statistics in Medicine with R"
  subtitle: "1st Edition"
  author: 
    - name: "Konstantinos I. Bougioukas, PhD"
      orcid: "0000-0002-6533-1391"
  date: today
  cover-image: images/cover.png
  favicon: images/cover.png
  chapters:
    - index.qmd
    - part: "Part 1: R Basics"
      chapters:
        - intro_rstudio.qmd
        - rstudio_projects.qmd
        - calculations.qmd
        - functions.qmd
        - packages.qmd
        - objects.qmd
        - vectors.qmd
        - matrices.qmd
        - lists.qmd
        - transformation.qmd 
        - ggplot2.qmd
    - part: "Part 2: Statistics"
      chapters:
        - introduction.qmd
        - descriptive.qmd
        - probability.qmd
        - prob_distributions.qmd
        - normal.qmd
        - inference.qmd
        - student_t_test.qmd
        - wmw_test.qmd
        - paired_t_test.qmd
        - wilcoxon_test.qmd
        - anova.qmd
        - kruskal_wallis.qmd
        - repeated_anova.qmd
        - friedman.qmd
        - correlation.qmd
        - simple_regression.qmd        
        - chi_square.qmd
        - fisher_exact.qmd
        - mcnemar.qmd
        - cochran.qmd
        - survival.qmd
        - measurement_properties.qmd
        - diagnostic_accuracy.qmd
        - roc.qmd
        - sample_size.qmd
    - references.qmd
    
  page-footer: 
    left: "Copyright 2023, Konstantinos I. Bougioukas" 
  back-to-top-navigation: true
  
bibliography: references.bib
reference-location: margin

filters:
  - social-share
  - lightbox
  - line-highlight

code-annotations: none

share:
  permalink: "https://practical-stats-med-r.netlify.app/"
  description: "Practical Statistics in Medicine with R"
  twitter: true
  facebook: true
  linkedin: true

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    grid:
      sidebar-width: 270px
      body-width: 840px
      margin-width: 250px
    fontsize: 1.25em
    linestretch: 1.8
    toc-title: "On this page"
    link-external-newwindow: true
    code-link: true
    number-depth: 2
    code-overflow: scroll
    html-math-method: mathjax
  
editor: visual