project:
  type: book
  output-dir: _book
book:
  title: "Practical Statistics in Medicine with R"
  subtitle: "Understanding Fundamental Concepts through Examples"
  author: 
    - name: "Konstantinos I. Bougioukas, PhD"
      orcid: "0000-0002-6533-1391"
  date: today
  cover-image: images/cover.png
  favicon: images/cover.png
  #sidebar:
    #logo: "images/lollipop2.png"
  chapters:
    - index.qmd
    - preface.qmd
    - author.qmd
    - rstudio.qmd
    - rproject.qmd
    - rcalculator.qmd
    - rfunctions.qmd
    - rpackages.qmd
    - robjects.qmd
    - rvectors.qmd
    - rmatrices.qmd
    - rlists.qmd
    - rtransformations.qmd
    - ggplot2.qmd
    - intro.qmd
    - probability.qmd
    - distributions.qmd
    - survival.qmd
    - diagnostic.qmd
    - references.qmd
    
  page-footer: 
    left: "Copyright 2025, Konstantinos I. Bougioukas" 
  back-to-top-navigation: true

crossref:
  fig-title: "**FIGURE**"
  fig-prefix: "Figure"
  tbl-title: "**TABLE**"
  tbl-prefix: "Table"
  title-delim: ""
  eq-prefix: "Eq."
  
bibliography: references.bib
reference-location: margin

filters:
  - line-highlight

code-annotations: none

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    grid:
      sidebar-width: 250px
      body-width: 890px
      margin-width: 250px
    fontsize: 1.20em
    linestretch: 1.5
    toc-title: "On this page"
    link-external-newwindow: true
    code-link: true
    number-depth: 5
    code-overflow: scroll
    html-math-method: mathjax

editor: visual