# About the Author {.unnumbered}

[Konstantinos I. Bougioukas](https://orcid.org/0000-0002-6533-1391) earned his PhD in Biostatistics and Research Methodology from the Faculty of Medicine at Aristotle University of Thessaloniki, Greece, in 2021. He has extensive experience teaching both basic and advanced Statistics. He has mentored and guided students and researchers from diverse scientific backgrounds, including—mathematics, medicine, biology, psychology, and health policy—in applying statistical methodologies and R programming.

As a research methodologist and data analyst, he specializes in evidence synthesis—including systematic reviews and meta-analyses, overviews of reviews, and meta-epidemiological studies—as well as advanced data analysis and data visualization techniques. He has authored over 40 peer-reviewed research [articles](https://bougioukas.github.io/mypage/publications.html) in high-impact academic journals such as *the British Medical Journal (the BMJ)*, *Research Synthesis Methods*, and *Journal of Clinical Epidemiology*. Additionally, he has contributed to the development of three open-source R packages: [“ccaR”, “amstar2Vis”, and “musicolor”](https://bougioukas.github.io/mypage/packages.html).
