<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>16&nbsp; Measures of diagnostic test accuracy – Practical Statistics in Medicine with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./survival.html" rel="prev">
<link href="./images/cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b2957c0d4a3fff488274d7c1181f6adc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/line-highlight-1.0.0/line-highlight.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./diagnostic.html"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Measures of diagnostic test accuracy</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Practical Statistics in Medicine with R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./author.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R via RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rproject.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">RStudio Projects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rcalculator.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R as Calculator</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rfunctions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">R Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rpackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">R packages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./robjects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">R objects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rvectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Atomic vectors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmatrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Matrices and arrays</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rlists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Lists and data frames</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rtransformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data import, pre-processing, and transformation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data visualization with ggplot2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introduction to Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Basic concepts of probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./diagnostic.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Measures of diagnostic test accuracy</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#contingency-2x2-table" id="toc-contingency-2x2-table" class="nav-link active" data-scroll-target="#contingency-2x2-table"><span class="header-section-number">16.1</span> Contingency 2x2 table</a></li>
  <li><a href="#diagnostic-accuracy-measures" id="toc-diagnostic-accuracy-measures" class="nav-link" data-scroll-target="#diagnostic-accuracy-measures"><span class="header-section-number">16.2</span> Diagnostic accuracy measures</a></li>
  <li>
<a href="#likelihood-ratios-in-practice" id="toc-likelihood-ratios-in-practice" class="nav-link" data-scroll-target="#likelihood-ratios-in-practice"><span class="header-section-number">16.3</span> Likelihood ratios in practice</a>
  <ul class="collapse">
<li><a href="#interpretation-of-lrs" id="toc-interpretation-of-lrs" class="nav-link" data-scroll-target="#interpretation-of-lrs"><span class="header-section-number">16.3.1</span> Interpretation of LRs</a></li>
  <li><a href="#application-of-lrs" id="toc-application-of-lrs" class="nav-link" data-scroll-target="#application-of-lrs"><span class="header-section-number">16.3.2</span> Application of LRs</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-diagnostic" class="quarto-section-identifier"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Measures of diagnostic test accuracy</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>In this chapter, we explore fundamental measures of diagnostic test accuracy, including sensitivity, specificity, positive predictive value (PPV), and negative predictive value (NPV). We also explain how to estimate post-test probabilities from pre-test probabilities and likelihood ratios, and we introduce Fagan’s Nomogram as a practical tool for clinicians.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Required packages for this chapter</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">epiR</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://here.r-lib.org/">here</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>&nbsp;</p>
<section id="contingency-2x2-table" class="level2" data-number="16.1"><h2 data-number="16.1" class="anchored" data-anchor-id="contingency-2x2-table">
<span class="header-section-number">16.1</span> Contingency 2x2 table</h2>
<p>An individual’s disease status is generally classified as either having the disease (<span class="math inline">\(Outcome+\)</span>) or not having the disease (<span class="math inline">\(Outcome-\)</span>), as determined by the reference standard (or “gold” standard). Depending on the type of diagnostic test under evaluation (also referred to as index test), the outcome may be measured as either dichotomous (e.g., the presence or absence of breast abnormalities detected through mammography) or continuous (e.g., breast tissue stiffness measured using elastography in ultrasound imaging). It is important to note that a continuous variable can be converted into a dichotomous outcome by selecting an optimal cut-off point (threshold) that distinguishes positive (<span class="math inline">\(Test+\)</span>) from negative (<span class="math inline">\(Test-\)</span>) test results.</p>
<p>When the index test provides a dichotomous result for each participant in a study, the data can be organized into a 2 x 2 table, comparing test results (<span class="math inline">\(Test+\)</span>, <span class="math inline">\(Test-\)</span>) with the “true” disease status (<span class="math inline">\(Outcome+\)</span>, <span class="math inline">\(Outcome-\)</span>). For example, the results of digital mammography test in 1220 women with suspected breast cancer, compared to the “gold” standard of biopsy/surgery and histopathology, are shown in <a href="#tbl-tbl1mamograph" class="quarto-xref">Table&nbsp;<span>16.1</span></a>.</p>
<p>&nbsp;</p>
<div id="tbl-tbl1mamograph" class="latex-table quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tbl1mamograph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>TABLE</strong>&nbsp;16.1 A 2 × 2 table reporting cross-classification of individuals by index test and reference standard result.
</figcaption><div aria-describedby="tbl-tbl1mamograph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="latex-table caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 10%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 18%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td colspan="2"><strong>According to the reference standard</strong></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>
<span class="math inline">\(Outcome+\)</span> (Disease present)</td>
<td>
<span class="math inline">\(Outcome-\)</span> (Disease absent)</td>
<td>Totals</td>
</tr>
<tr class="odd">
<td><strong>Index Test result</strong></td>
<td>
<p><span class="math inline">\(Test+\)</span></p>
<p><span class="math inline">\(Test-\)</span></p>
<p>Totals</p>
</td>
<td>
<p><strong>TP</strong>=890</p>
<p><strong>FN</strong>=20</p>
<p>TP+FN=910</p>
</td>
<td>
<p><strong>FP</strong>=110</p>
<p><strong>TN</strong>=200</p>
<p>TN+FP=310</p>
</td>
<td>
<p>TP+FP=1000</p>
<p>TN+FN=220</p>
<p><strong>N</strong>=1220 (TP+TN+FP+FN)</p>
</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong><em>Abbreviations:</em></strong> <strong>TP:</strong> true positive; test positive and disease present. <strong>FP:</strong> false positive; test positive and disease absent. <strong>FN:</strong> false negative; test negative and disease present. <strong>TN:</strong> true negative; test negative and disease absent.</p>
<p>&nbsp;</p>
<p><strong>In R:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">tb1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">as.table</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">890</span>, <span class="fl">110</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">20</span>, <span class="fl">200</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">tb1</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>Test <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Test +"</span>, <span class="st">"Test -"</span><span class="op">)</span>,</span>
<span>                      Outcome <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Outcome +"</span>, <span class="st">"Outcome -"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">tb1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code>        Outcome
Test     Outcome + Outcome -
  Test +       890       110
  Test -        20       200</code></pre>
</div>
</div>
<p>From this contingency table, we can create a mosaic plot in base R using the <strong><code><a href="https://rdrr.io/r/graphics/mosaicplot.html">mosaicplot()</a></code></strong> function (<a href="#fig-mosaic01" class="quarto-xref">Figure&nbsp;<span>16.1</span></a>).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/graphics/mosaicplot.html">mosaicplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">tb1</span><span class="op">)</span>, col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"gray90"</span>, <span class="st">"gray30"</span><span class="op">)</span>, </span>
<span>           cex.axis <span class="op">=</span> <span class="fl">1.1</span>, main<span class="op">=</span><span class="cn">NULL</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-mosaic01" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mosaic01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="diagnostic_files/figure-html/fig-mosaic01-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" data-fig-pos="H" width="624">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosaic01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;16.1 Mosaic plot of the 2x2 table for the results of the digital mammography test.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="diagnostic-accuracy-measures" class="level2" data-number="16.2"><h2 data-number="16.2" class="anchored" data-anchor-id="diagnostic-accuracy-measures">
<span class="header-section-number">16.2</span> Diagnostic accuracy measures</h2>
<p>The basic diagnostic accuracy measures are:</p>
<ul>
<li>
<p><strong>Sensitivity (Se):</strong> The ability of the diagnostic test to correctly identify individuals with the disease. It is defined as the proportion of true positive test results among individuals who have the disease (“true positive rate”).</p>
<p><span class="math inline">\(Se = P(Test+|Disease+) = \frac{TP}{TP+FN}=\frac{890}{910}=0.978 \ \ \text{or} \ \ 97.8\%\)</span></p>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>
<p>The <strong>Specificity (Sp):</strong> The ability of the diagnostic test to correctly identify individuals without the disease. It is defined as the proportion of true negative test results among individuals who do not have the disease (“true negative rate”).</p>
<p><span class="math inline">\(Sp = P(Test-|Disease-) = \frac{TN}{TN+FP}=\frac{200}{310}=0.645 \ \ \text{or} \ \ 64.5\%\)</span></p>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>
<p><strong>Positive Predictive Value (PPV):</strong> The probability of presence of disease given a positive test result. It is defined as the proportion of true positive test results among individuals who have a positive test.</p>
<p><span class="math inline">\(PPV = P(Disease+|Test+) =\frac{TP}{TP+FP}=\frac{890}{1000}=0.890 \ \ \text{or} \ \ 89.0\%\)</span></p>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>
<p><strong>Negative Predictive Value (NPV):</strong> The probability of absence of disease given a negative test result. It is defined as the proportion of true negative test results among individuals who have a negative test.</p>
<p><span class="math inline">\(NPV = P(Disease-|Test-)=\frac{TN}{TN+FN}=\frac{200}{220}=0.909 \ \ \text{or} \ \ 90.9\%\)</span></p>
</li>
</ul>
<div class="content-box-gray">
<p><strong>IMPORTANT</strong></p>
<p>Positive and negative predictive values (PPV and NPV) are directly influenced by the <strong>prevalence</strong> of disease in the <strong>population</strong> being tested. When the same test is applied to a population with a higher prevalence (e.g., women over the age of 55 years), the PPV increases while the NPV decreases. Therefore, when evaluating predictive values of diagnostic or screening tests, it is essential to consider the impact of disease prevalence.</p>
</div>
<p>&nbsp;</p>
<p>Other useful diagnostic measures include the following:</p>
<ul>
<li>
<p><strong>Apparent prevalence:</strong> The proportion of individuals with a positive test result.</p>
<p><span class="math inline">\(Apparent \ prevalence = \frac{TP + FP}{N}=\frac{1000}{1220}=0.820 \ \ \text{or} \ \ 82.0\%\)</span></p>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>
<p><strong>True prevalence:</strong> The proportion of individuals that are truly diseased.</p>
<p><span class="math inline">\(True \ prevalence = \frac{TP + FN}{N}=\frac{910}{1220}=0.746 \ \ \text{or} \ \ 74.6\%\)</span></p>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>
<p><strong>Likelihood ratio for a positive test result (LR+):</strong> The probability of a positive test in individuals with the disease divided by the probability of a positive test in individuals without the disease. It is calculated as <span class="math inline">\(Se/(1-Sp)\)</span>:</p>
<p><span class="math inline">\(LR+ = \frac{P(Test+|Disease+)}{P(Test+|Disease-)} = \frac{Se}{1-Sp}=\frac{0.978}{1-0.645}=\frac{0.978}{0.355}= 2.755\)</span></p>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>
<p><strong>Likelihood ratio for a negative test result (LR-):</strong> The probability of a negative test in individuals with the disease divided by the probability of a negative test in individuals without the disease. It is calculated as <span class="math inline">\((1-Se)/Sp\)</span>:</p>
<p><span class="math inline">\(LR- = \frac{P(Test-|Disease+)}{P(Test-|Disease-)}= \frac{1-Se}{Sp}=\frac{1-0.978}{0.645}=\frac{0.022}{0.645}= 0.034\)</span></p>
</li>
</ul>
<p>&nbsp;</p>
<ul>
<li>
<p><strong>Diagnostic accuracy</strong> (effectiveness), expressed as a proportion of correctly classified subjects (TP+TN) among all subjects (N). Diagnostic accuracy is affected by the disease prevalence.</p>
<p><span class="math inline">\(Accuracy = \frac{TP + TN}{N}=\frac{890 + 200}{1220}=\frac{1090}{1220}= 0.893 \ \ \text{or} \ \ 89.3\%\)</span></p>
</li>
</ul>
<p>&nbsp;</p>
<p><strong>In R:</strong></p>
<p>The <strong><code><a href="https://rdrr.io/pkg/epiR/man/epi.tests.html">epi.tests()</a></code></strong> function computes all the above epidemiological statistics based on the 2x2 contingency table.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/epiR/man/epi.tests.html">epi.tests</a></span><span class="op">(</span><span class="va">tb1</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code>          Outcome +    Outcome -      Total
Test +          890          110       1000
Test -           20          200        220
Total           910          310       1220

Point estimates and 95% CIs:
--------------------------------------------------------------
Apparent prevalence *                  0.820 (0.797, 0.841)
True prevalence *                      0.746 (0.720, 0.770)
Sensitivity *                          0.978 (0.966, 0.987)
Specificity *                          0.645 (0.589, 0.698)
Positive predictive value *            0.890 (0.869, 0.909)
Negative predictive value *            0.909 (0.863, 0.944)
Positive likelihood ratio              2.756 (2.371, 3.204)
Negative likelihood ratio              0.034 (0.022, 0.053)
False T+ proportion for true D- *      0.355 (0.302, 0.411)
False T- proportion for true D+ *      0.022 (0.013, 0.034)
False T+ proportion for T+ *           0.110 (0.091, 0.131)
False T- proportion for T- *           0.091 (0.056, 0.137)
Correctly classified proportion *      0.893 (0.875, 0.910)
--------------------------------------------------------------
* Exact CIs</code></pre>
</div>
</div>
<p>&nbsp;</p>
<p>Sensitivity, specificity, and likelihood ratio (LR) are generally considered intrinsic characteristics of the test that are independent of disease prevalence. However, it is important to note that several studies have identified potential mechanisms through which variations in disease prevalence can influence these measures <span class="citation" data-cites="brenner1997 li2011 leeflang2013 murad2023">(<a href="references.html#ref-brenner1997" role="doc-biblioref">Brenner and Gefeller 1997</a>; <a href="references.html#ref-li2011" role="doc-biblioref">Li and Fine 2011</a>; <a href="references.html#ref-leeflang2013" role="doc-biblioref">Leeflang et al. 2013</a>; <a href="references.html#ref-murad2023" role="doc-biblioref">Murad et al. 2023</a>)</span>.</p>
<p>&nbsp;</p>
</section><section id="likelihood-ratios-in-practice" class="level2" data-number="16.3"><h2 data-number="16.3" class="anchored" data-anchor-id="likelihood-ratios-in-practice">
<span class="header-section-number">16.3</span> Likelihood ratios in practice</h2>
<section id="interpretation-of-lrs" class="level3" data-number="16.3.1"><h3 data-number="16.3.1" class="anchored" data-anchor-id="interpretation-of-lrs">
<span class="header-section-number">16.3.1</span> Interpretation of LRs</h3>
<p>Let’s elaborate on the meaning of the LR in our example with the digital mammography test.</p>
<p>An LR+ of 2.756 means that a positive result in digital mammography is approximately 2.8 times more likely to occur in individuals with breast cancer than in individuals without breast cancer.</p>
<p>An LR- of 0.034 means that a negative result in the digital mammography is 0.034 times as likely to occur in individuals with breast cancer as it is in individuals without breast cancer. This can also be interpreted as follows: a negative mammography result is approximately 29.4 times (1/0.034) more likely in a woman without breast cancer than in a woman with breast cancer.</p>
<div class="content-box-gray">
<p><strong>IMPORTANT</strong></p>
<ul>
<li><p>Every diagnostic test is associated with both LR+ and LR-.</p></li>
<li><p>In clinical practice, a higher LR+ is desirable for tests used to “rule in” a disease, while a lower LR- is preferred for tests used to “rule out” the possibility that the individual has the disease.</p></li>
<li><p>Values very close to 1 (for either LR+ or LR-) indicate that the test has limited diagnostic value, as it does not meaningfully alter the probability of disease.</p></li>
</ul>
</div>
<p>&nbsp;</p>
</section><section id="application-of-lrs" class="level3" data-number="16.3.2"><h3 data-number="16.3.2" class="anchored" data-anchor-id="application-of-lrs">
<span class="header-section-number">16.3.2</span> Application of LRs</h3>
<p>The LR is commonly used in decision-making based on Bayes’ Theorem. The pre-test odds of a particular diagnosis, multiplied by the likelihood ratio of the diagnostic test, determines the post-test odds.</p>
<p><span id="eq-posteq1"><span class="math display">\[
post \text{-} test \ odds = likelihood \ ratio \times pre \text{-} test \ odds
\tag{16.1}\]</span></span></p>
<p>where the <span class="math inline">\(\times\)</span> symbol denotes multiplication.</p>
<p>These post-test odds provides an updated estimate of the odds that the patient has the condition or disease after taking into account the diagnostic test result. If the test result is positive, we use the LR+ for this calculation. If the test result is negative, we use the LR- instead. In both scenarios, the odds refer to the odds in favor of the disease <strong>being present</strong>.</p>
<p>&nbsp;</p>
<section id="lr-example" class="level4" data-number="16.3.2.1"><h4 data-number="16.3.2.1" class="anchored" data-anchor-id="lr-example">
<span class="header-section-number">16.3.2.1</span> LR+ example</h4>
<p>LR+ indicates how much the odds of the condition or disease being present increase after a positive test result (Range: 1 to <span class="math inline">\(+ \infty\)</span>).</p>
<ul>
<li><p><strong>LR+ &gt; 1:</strong> Indicates that a positive test result increases the post-test odds of the disease being present. The higher the LR+, the more informative the test is for ruling in the disease.</p></li>
<li><p><strong>LR+ = 1:</strong> Indicates that a positive test result does not change the post-test odds compared to the pre-test odds. In other words, a diagnostic test with an LR+ of 1 provides no additional information about the likelihood of the disease and has no diagnostic value.</p></li>
</ul>
<p>&nbsp;</p>
<p>Let’s suppose that, based on her family history of breast cancer and clinical symptoms, a woman has a high probability of having breast cancer, estimated at 0.78 (pre-test probability).</p>
<div class="content-box-white">
<p><strong>INFO</strong></p>
<p>Pre-test probability refers to the probability that a patient has the disease before the result of the diagnostic test is known. This probability can be estimated using clinical judgment or derived from research evidence, such as disease prevalence and clinical prediction rules <span class="citation" data-cites="uy2022">(<a href="references.html#ref-uy2022" role="doc-biblioref">Uy 2022</a>)</span>.</p>
</div>
<p>We are interested in the the <strong>post-test probability</strong> of breast cancer when the digital mammography is <strong>positive</strong>. It is important to note that “odds” and “probability” are not the same; however, they can be derived from each other as follows:</p>
<p><span class="math inline">\(pre \text{-} test \ odds = \frac{pre \text{-} test \ probability}{1 - pre \text{-} test \ probability} = \frac{0.78}{1-0.78} = \frac{0.78}{0.22} = 3.55\)</span></p>
<p><span class="math inline">\(post \text{-} test \ odds = LR\text{+} \times pre \text{-} test \ odds = 2.756 \times 3.55 = 9.78\)</span></p>
<p><span class="math inline">\(post \text{-} test \ probability = \frac{post \text{-} test \ odds}{post \text{-} test \ odds + 1} = \frac{9.78}{9.78 + 1} = \frac{9.78}{10.78} = 0.9072 \ \ \text{or} \ \ 90.72\%\)</span></p>
<p>Thus, after considering the positive digital mammography test result, the woman’s probability of having breast cancer increases from 78% to approximately 90.7%.</p>
<p>The Fagan nomogram allows us to turn pre-test probabilities into post-test probabilities without needing to convert into odds. The nomogram typically consists of three parallel scales representing the pre-test probability, the likelihood ratio, and the post-test probability. We can visually estimate the post-test probability of a positive diagnosis result by drawing a line from the known pre-test probability, through the LR+ and read off the post-test probability (<a href="#fig-fagan1" class="quarto-xref">Figure&nbsp;<span>16.2</span></a>a).</p>
<p>&nbsp;</p>
</section><section id="lr--example" class="level4" data-number="16.3.2.2"><h4 data-number="16.3.2.2" class="anchored" data-anchor-id="lr--example">
<span class="header-section-number">16.3.2.2</span> LR- example</h4>
<p>LR- indicates how much the odds of the condition or disease being present decrease after a negative test result (Range: 0 to 1).</p>
<ul>
<li><p><strong>LR- &lt; 1:</strong> Indicates that a negative test result decreases the post-test odds of the disease being present. The lower the LR-, the more informative the test is for ruling out the disease.</p></li>
<li><p><strong>LR- = 1:</strong> Indicates that a negative test result does not change the post-test odds compared to the pre-test odds. In other words, a diagnostic test with an LR- of 1 provides no additional information about the likelihood of the disease and has no diagnostic value.</p></li>
</ul>
<p>&nbsp;</p>
<p>What is the the post-test probability of breast cancer for the same woman when the digital mammography is <strong>negative</strong>?</p>
<p><span class="math inline">\(post \text{-} test \ odds = LR\text{-} \times pre \text{-} test \ odds = 0.034 \times 3.55 = 0.1207\)</span></p>
<p><span class="math inline">\(post \text{-} test \ probability = \frac{post \text{-} test \ odds}{post \text{-} test \ odds + 1} = \frac{0.1207}{0.1207 + 1} = \frac{0.1207}{1.1207} = 0.1077 \ \ \text{or} \ \ 10.77\%\)</span></p>
<p>The result indicates that after considering the negative digital mammography test result, the woman’s probability of having breast cancer drops significantly from 78% to approximately 10.8% (<a href="#fig-fagan1" class="quarto-xref">Figure&nbsp;<span>16.2</span></a>b).</p>
<p>&nbsp;</p>
<div id="fig-fagan1" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-fagan1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fagan1" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-fagan1-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="100%">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-fagan1-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="diagnostic_files/figure-html/fig-fagan1-1.png" id="fig-fagan1-1" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" style="width:100.0%" data-fig-pos="H" data-ref-parent="fig-fagan1">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-fagan1-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a)
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-fagan1" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-fagan1-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" width="100%">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-fagan1-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="diagnostic_files/figure-html/fig-fagan1-2.png" id="fig-fagan1-2" class="img-fluid quarto-figure quarto-figure-center anchored figure-img" style="width:100.0%" data-fig-pos="H" data-ref-parent="fig-fagan1">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-fagan1-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b)
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fagan1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;16.2 Fagan Nomogram illustrating the impact of digital mammography results on breast cancer probability. This figure demonstrates how an initial pre-test probability of 78% is updated to (a) a post-test probability of 90.7% following a positive mammography result with an LR+ of 2.76, and (b) a post-test probability of 10.8% following a negative mammography result with an LR- of 0.034.
</figcaption></figure>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-brenner1997" class="csl-entry" role="listitem">
Brenner, Hermann, and Olaf Gefeller. 1997. <span>“VARIATION OF SENSITIVITY, SPECIFICITY, LIKELIHOOD RATIOS AND PREDICTIVE VALUES WITH DISEASE PREVALENCE.”</span> <em>Statistics in Medicine</em> 16 (9): 981–91. <a href="https://doi.org/10.1002/(sici)1097-0258(19970515)16:9<981::aid-sim510>3.0.co;2-n">https://doi.org/10.1002/(sici)1097-0258(19970515)16:9&lt;981::aid-sim510&gt;3.0.co;2-n</a>.
</div>
<div id="ref-leeflang2013" class="csl-entry" role="listitem">
Leeflang, Mariska M. G., Anne W. S. Rutjes, Johannes B. Reitsma, Lotty Hooft, and Patrick M. M. Bossuyt. 2013. <span>“Variation of a Test<span>’</span>s Sensitivity and Specificity with Disease Prevalence.”</span> <em>Canadian Medical Association Journal</em> 185 (11): E537–44. <a href="https://doi.org/10.1503/cmaj.121286">https://doi.org/10.1503/cmaj.121286</a>.
</div>
<div id="ref-li2011" class="csl-entry" role="listitem">
Li, J., and J. P. Fine. 2011. <span>“Assessing the Dependence of Sensitivity and Specificity on Prevalence in Meta-Analysis.”</span> <em>Biostatistics</em> 12 (4): 710–22. <a href="https://doi.org/10.1093/biostatistics/kxr008">https://doi.org/10.1093/biostatistics/kxr008</a>.
</div>
<div id="ref-murad2023" class="csl-entry" role="listitem">
Murad, M. Hassan, Lifeng Lin, Haitao Chu, Bashar Hasan, Reem A. Alsibai, Alzhraa S. Abbas, Reem A. Mustafa, and Zhen Wang. 2023. <span>“The Association of Sensitivity and Specificity with Disease Prevalence: Analysis of 6909 Studies of Diagnostic Test Accuracy.”</span> <em>Canadian Medical Association Journal</em> 195 (27): E925–31. <a href="https://doi.org/10.1503/cmaj.221802">https://doi.org/10.1503/cmaj.221802</a>.
</div>
<div id="ref-uy2022" class="csl-entry" role="listitem">
Uy, Elenore Judy B. 2022. <span>“Key Concepts in Clinical Epidemiology: Estimating Pre-Test Probability.”</span> <em>Journal of Clinical Epidemiology</em> 144 (April): 198–202. <a href="https://doi.org/10.1016/j.jclinepi.2021.10.022">https://doi.org/10.1016/j.jclinepi.2021.10.022</a>.
</div>
</div>
</section></section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./survival.html" class="pagination-link" aria-label="Survival Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Konstantinos I. Bougioukas</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


<script src="site_libs/quarto-contrib/line-highlight-1.0.0/line-highlight.js" defer="true"></script>
</body></html>