<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>10&nbsp; Data import, pre-processing, and transformation – Practical Statistics in Medicine with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./ggplot2.html" rel="next">
<link href="./rlists.html" rel="prev">
<link href="./images/cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b2957c0d4a3fff488274d7c1181f6adc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/line-highlight-1.0.0/line-highlight.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./rtransformations.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data import, pre-processing, and transformation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Practical Statistics in Medicine with R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./author.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R via RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rproject.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">RStudio Projects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rcalculator.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R as Calculator</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rfunctions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">R Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rpackages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">R packages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./robjects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">R objects</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rvectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Atomic vectors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmatrices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Matrices and arrays</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rlists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Lists and data frames</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rtransformations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data import, pre-processing, and transformation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ggplot2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data visualization with ggplot2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introduction to Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Basic concepts of probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./diagnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Measures of diagnostic test accuracy</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#importing-data" id="toc-importing-data" class="nav-link active" data-scroll-target="#importing-data"><span class="header-section-number">10.1</span> Importing data</a>
  <ul class="collapse">
<li><a href="#importing-data-from-excel-using-the-rstudio-interface" id="toc-importing-data-from-excel-using-the-rstudio-interface" class="nav-link" data-scroll-target="#importing-data-from-excel-using-the-rstudio-interface"><span class="header-section-number">10.1.1</span> Importing data from Excel using the RStudio Interface</a></li>
  <li><a href="#importing-data-from-excel-into-r-with-commands" id="toc-importing-data-from-excel-into-r-with-commands" class="nav-link" data-scroll-target="#importing-data-from-excel-into-r-with-commands"><span class="header-section-number">10.1.2</span> Importing data from Excel into R with commands</a></li>
  </ul>
</li>
  <li>
<a href="#pre-processing-data" id="toc-pre-processing-data" class="nav-link" data-scroll-target="#pre-processing-data"><span class="header-section-number">10.2</span> Pre-processing data</a>
  <ul class="collapse">
<li><a href="#adding-an-unique-identifier-for-each-observation" id="toc-adding-an-unique-identifier-for-each-observation" class="nav-link" data-scroll-target="#adding-an-unique-identifier-for-each-observation"><span class="header-section-number">10.2.1</span> Adding an unique identifier for each observation</a></li>
  <li><a href="#renaming-variables-and-cleaning-names" id="toc-renaming-variables-and-cleaning-names" class="nav-link" data-scroll-target="#renaming-variables-and-cleaning-names"><span class="header-section-number">10.2.2</span> Renaming variables and cleaning names</a></li>
  <li><a href="#converting-to-the-appropriate-data-type" id="toc-converting-to-the-appropriate-data-type" class="nav-link" data-scroll-target="#converting-to-the-appropriate-data-type"><span class="header-section-number">10.2.3</span> Converting to the appropriate data type</a></li>
  <li><a href="#handling-missing-values" id="toc-handling-missing-values" class="nav-link" data-scroll-target="#handling-missing-values"><span class="header-section-number">10.2.4</span> Handling missing values</a></li>
  </ul>
</li>
  <li>
<a href="#transforming-data" id="toc-transforming-data" class="nav-link" data-scroll-target="#transforming-data"><span class="header-section-number">10.3</span> Transforming data</a>
  <ul class="collapse">
<li><a href="#subsetting-observations-rows" id="toc-subsetting-observations-rows" class="nav-link" data-scroll-target="#subsetting-observations-rows"><span class="header-section-number">10.3.1</span> Subsetting observations (rows)</a></li>
  <li><a href="#reordering-observations-rows" id="toc-reordering-observations-rows" class="nav-link" data-scroll-target="#reordering-observations-rows"><span class="header-section-number">10.3.2</span> Reordering observations (rows)</a></li>
  <li><a href="#subsetting-variables-columns" id="toc-subsetting-variables-columns" class="nav-link" data-scroll-target="#subsetting-variables-columns"><span class="header-section-number">10.3.3</span> Subsetting variables (columns)</a></li>
  <li><a href="#creating-new-variables" id="toc-creating-new-variables" class="nav-link" data-scroll-target="#creating-new-variables"><span class="header-section-number">10.3.4</span> Creating new variables</a></li>
  <li><a href="#using-the-native-pipe-operator-in-a-sequence-of-commands" id="toc-using-the-native-pipe-operator-in-a-sequence-of-commands" class="nav-link" data-scroll-target="#using-the-native-pipe-operator-in-a-sequence-of-commands"><span class="header-section-number">10.3.5</span> Using the native pipe operator in a sequence of commands</a></li>
  </ul>
</li>
  <li>
<a href="#summarizing-data" id="toc-summarizing-data" class="nav-link" data-scroll-target="#summarizing-data"><span class="header-section-number">10.4</span> Summarizing data</a>
  <ul class="collapse">
<li><a href="#summary-measures" id="toc-summary-measures" class="nav-link" data-scroll-target="#summary-measures"><span class="header-section-number">10.4.1</span> Summary measures</a></li>
  <li><a href="#frequency-statistics" id="toc-frequency-statistics" class="nav-link" data-scroll-target="#frequency-statistics"><span class="header-section-number">10.4.2</span> Frequency Statistics</a></li>
  </ul>
</li>
  <li>
<a href="#reshaping-data" id="toc-reshaping-data" class="nav-link" data-scroll-target="#reshaping-data"><span class="header-section-number">10.5</span> Reshaping data</a>
  <ul class="collapse">
<li><a href="#from-wide-to-long-format" id="toc-from-wide-to-long-format" class="nav-link" data-scroll-target="#from-wide-to-long-format"><span class="header-section-number">10.5.1</span> From wide to long format</a></li>
  <li><a href="#from-long-to-wide-format" id="toc-from-long-to-wide-format" class="nav-link" data-scroll-target="#from-long-to-wide-format"><span class="header-section-number">10.5.2</span> From long to wide format</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-rtransformations" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Data import, pre-processing, and transformation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>This chapter focuses on importing data from spreadsheets into R and covers essential techniques for manipulating, transforming, and summarizing data effectively. We also introduce the powerful native forward pipe operator <code>|&gt;</code>, which streamlines the process by allowing operations to be chained together in a clear and concise manner. Additionally, we present and explain the process of reshaping data between wide and long formats in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Required packages for this chapter</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org">readxl</a></span><span class="op">)</span>              </span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/sfirke/janitor">janitor</a></span><span class="op">)</span>             </span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://here.r-lib.org/">here</a></span><span class="op">)</span> </span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>&nbsp;</p>
<section id="importing-data" class="level2" data-number="10.1"><h2 data-number="10.1" class="anchored" data-anchor-id="importing-data">
<span class="header-section-number">10.1</span> Importing data</h2>
<p>Spreadsheets are commonly used to organize structured, rectangular data and are available in formats such as Excel, CSV, or Google Sheets. Each format offers unique features, from Excel’s comprehensive capabilities to CSV’s simplicity and Google Sheets’ collaborative editing. In this textbook, most <a href="https://osf.io/3amrb/files/osfstorage">datasets</a> are provided in Excel files (<code>.xlsx</code>) and typically have the following basic characteristics:</p>
<ul>
<li>The first line in the file is a <em>header</em> row, specifying the names of the columns (variables).</li>
<li>Each value has its own cell.</li>
<li>Missing values are represented as empty cells.</li>
</ul>
<p>For example, <a href="#fig-excel" class="quarto-xref">Figure&nbsp;<span>10.1</span></a> shows a screenshot of data from a single sheet of an Excel file. The dataset, named <code>shock_index</code>, contains information about the characteristics of 30 adult patients suspected of having a pulmonary embolism. The following variables were recorded:</p>
<ul>
<li>
<strong>sex:</strong> F for females and M for males</li>
<li>
<strong>Age:</strong> age of the patients in years</li>
<li>
<strong>SBP:</strong> systolic blood pressure in mmHg</li>
<li>
<strong>HR:</strong> resting heart rate in beats/min</li>
</ul>
<div id="fig-excel" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-excel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/excel.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-excel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.1 Screenshot of an Excel file.
</figcaption></figure>
</div>
<section id="importing-data-from-excel-using-the-rstudio-interface" class="level3" data-number="10.1.1"><h3 data-number="10.1.1" class="anchored" data-anchor-id="importing-data-from-excel-using-the-rstudio-interface">
<span class="header-section-number">10.1.1</span> Importing data from Excel using the RStudio Interface</h3>
<p>To import data using the RStudio interface, we navigate to the Environment pane, where we’ll find the “Import Dataset” button. Clicking this button will prompt a dropdown menu with options to import data from various file formats such as CSV, Excel, or other common formats. We select “From Excel…” (<a href="#fig-import" class="quarto-xref">Figure&nbsp;<span>10.2</span></a>).</p>
<div id="fig-import" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-import-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/import.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-import-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.2 Importing data using the RStudio interface.
</figcaption></figure>
</div>
<p>A dialog box then appears, enabling us to navigate our file system and specify the desired dataset (<a href="#fig-wizard" class="quarto-xref">Figure&nbsp;<span>10.3</span></a>). Once selected, we confirm the import by clicking “Open”. Finally, we proceed by clicking the “Import” button, which imports the selected dataset into our RStudio session.”</p>
<div id="fig-wizard" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-wizard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/wizard.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wizard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.3 Specifying the dataset for import.
</figcaption></figure>
</div>
<p>After a successful import, the dataset will be displayed in the Environment pane, allowing for further manipulation.</p>
</section><section id="importing-data-from-excel-into-r-with-commands" class="level3" data-number="10.1.2"><h3 data-number="10.1.2" class="anchored" data-anchor-id="importing-data-from-excel-into-r-with-commands">
<span class="header-section-number">10.1.2</span> Importing data from Excel into R with commands</h3>
<p>Alternatively, if the dataset is saved in the subfolder named “data” of our RStudio project (see also <a href="rproject.html" class="quarto-xref"><span>Chapter 2</span></a>), we can read it with the <strong><code><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel()</a></code></strong> function from <strong><em>readxl</em></strong> package as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel</a></span><span class="op">(</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"shock_index.xlsx"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The path of a file (directory) is its location in the file system (address). As we have previously discussed, there are two kinds of paths.</p>
<ul>
<li>absolute paths such as “<code>C:/My_name/../my_project/data/shock_index.xlsx</code>” and</li>
<li>relative paths such as “<code>data/shock_index.xlsx</code>”.</li>
</ul>
<p>The function <code><a href="https://here.r-lib.org/reference/here.html">here()</a></code> allows us to navigate throughout each of the subfolders and files within a given RStudio Project using <em>relative paths</em> (see also <a href="rpackages.html" class="quarto-xref"><span>Chapter 5</span></a>).</p>
<p>Using <strong><code><a href="https://rdrr.io/r/utils/head.html">head()</a></code></strong> is a convenient way to get a quick overview of our dataset and check for any obvious issues before proceeding with further analysis or data manipulation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 4
  sex     Age   SBP    HR
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 M        54   139    85
2 F        47   151    84
3 F        58   200   100
4 M        NA   170    56
5 F        60   123    55
6 F        57   121    90</code></pre>
</div>
</div>
<p>By default, the <strong>first six</strong> rows of the data frame are displayed. To view a different number of rows (e.g., the first ten), we can specify the desired number as an argument, like this: <code>head(dat, 10)</code>.</p>
<p>Additionally, when working with large datasets in R, it’s often useful to inspect the last few rows of a data frame. The <strong><code>tail(</code>)</strong> function is used for this purpose:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 4
  sex     Age   SBP    HR
  &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 M        58   119    87
2 F        48   104    93
3 F        55   164    69
4 M        59    92   119
5 F        48   127   109
6 F        51   136    60</code></pre>
</div>
</div>
<p>Now, the <strong>last six</strong> rows of the data frame are displayed in the R console.</p>
<p><br></p>
</section></section><section id="pre-processing-data" class="level2" data-number="10.2"><h2 data-number="10.2" class="anchored" data-anchor-id="pre-processing-data">
<span class="header-section-number">10.2</span> Pre-processing data</h2>
<section id="adding-an-unique-identifier-for-each-observation" class="level3" data-number="10.2.1"><h3 data-number="10.2.1" class="anchored" data-anchor-id="adding-an-unique-identifier-for-each-observation">
<span class="header-section-number">10.2.1</span> Adding an unique identifier for each observation</h3>
<p>A unique identifier for each observation is often useful for various data manipulation and analysis tasks. In R, we can add row numbers starting from 1 to the number of rows in our data frame using the <strong><code><a href="https://tibble.tidyverse.org/reference/rownames.html">rowid_to_column()</a></code></strong> function from the <strong><em>tibble</em></strong> package:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">rowid_to_column</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 5
  rowid sex     Age   SBP    HR
  &lt;int&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1 M        54   139    85
2     2 F        47   151    84
3     3 F        58   200   100
4     4 M        NA   170    56
5     5 F        60   123    55
6     6 F        57   121    90</code></pre>
</div>
</div>
</section><section id="renaming-variables-and-cleaning-names" class="level3" data-number="10.2.2"><h3 data-number="10.2.2" class="anchored" data-anchor-id="renaming-variables-and-cleaning-names">
<span class="header-section-number">10.2.2</span> Renaming variables and cleaning names</h3>
<p>Choosing informative column names can significantly enhance the clarity and interpretability of our dataset. For instance, renaming <code>rowid</code> to <code>patient_ID</code> clarifies that this column serves as a unique identifier for each patient. Likewise, renaming <code>HR</code> to <code>Heart.Rate</code> offers a more intuitive and informative label for the heart rate variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span><span class="va">dat</span>, </span>
<span>               patient_ID <span class="op">=</span> <span class="va">rowid</span>,</span>
<span>               Heart.Rate <span class="op">=</span> <span class="va">HR</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 5
  patient_ID sex     Age   SBP Heart.Rate
       &lt;int&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1          1 M        54   139         85
2          2 F        47   151         84
3          3 F        58   200        100
4          4 M        NA   170         56
5          5 F        60   123         55
6          6 F        57   121         90</code></pre>
</div>
</div>
<p>However, it’s crucial to ensure that the column names are consistent with the naming conventions in R. This can be achieved by using the <strong><code><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names()</a></code></strong> function from the <strong><em>janitor</em></strong> package, which standardizes column names by converting them to lowercase, removing special characters, and replacing spaces with underscores.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://sfirke.github.io/janitor/reference/clean_names.html">clean_names</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 5
  patient_id sex     age   sbp heart_rate
       &lt;int&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1          1 M        54   139         85
2          2 F        47   151         84
3          3 F        58   200        100
4          4 M        NA   170         56
5          5 F        60   123         55
6          6 F        57   121         90</code></pre>
</div>
</div>
</section><section id="converting-to-the-appropriate-data-type" class="level3" data-number="10.2.3"><h3 data-number="10.2.3" class="anchored" data-anchor-id="converting-to-the-appropriate-data-type">
<span class="header-section-number">10.2.3</span> Converting to the appropriate data type</h3>
<p>We might have noticed that the categorical variable <code>sex</code> is coded as F (for females) and M (for males), so it is recognized of <code>character</code> type. We can use the <code><a href="https://rdrr.io/r/base/factor.html">factor()</a></code> function to encode a variable as a factor:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span><span class="op">$</span><span class="va">sex</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">sex</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"F"</span>, <span class="st">"M"</span><span class="op">)</span>, labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"female"</span>, <span class="st">"male"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 5
  patient_id sex      age   sbp heart_rate
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1          1 male      54   139         85
2          2 female    47   151         84
3          3 female    58   200        100
4          4 male      NA   170         56
5          5 female    60   123         55
6          6 female    57   121         90</code></pre>
</div>
</div>
</section><section id="handling-missing-values" class="level3" data-number="10.2.4"><h3 data-number="10.2.4" class="anchored" data-anchor-id="handling-missing-values">
<span class="header-section-number">10.2.4</span> Handling missing values</h3>
<p>Upon reviewing the dataset, it’s apparent that there are missing values in the <code>age</code> variable, denoted as <code>NA</code>. Various techniques exist to handle missing values in data such as excluding observations with any missing values, substituting with a constant value (mean, median, mode), or employing multiple imputation methods. The choice of method depends on factors such as the proportion of missing data, its distribution, and understanding the underlying mechanism behind the missingness (whether it’s random or non-random) <span class="citation" data-cites="altman2007 heymans2022">(<a href="references.html#ref-altman2007" role="doc-biblioref">Altman and Bland 2007</a>; <a href="references.html#ref-heymans2022" role="doc-biblioref">Heymans and Twisk 2022</a>)</span>.</p>
<p>While this introductory textbook primarily uses datasets without missing values, it’s important to note that missing data present a frequent challenge in real-world data analysis. Fortunately, several R packages are tailored to address this issue, including: <a href="https://amices.org/mice/"><strong><code>mice</code></strong></a>, <a href="https://statistikat.github.io/VIM/index.html"><strong><code>VIM</code></strong></a>, <a href="https://naniar.njtierney.com/index.html"><strong><code>naniar</code></strong></a>, and <a href="https://hbiostat.org/r/hmisc/"><strong><code>Hmisc</code></strong></a>.</p>
<p>&nbsp;</p>
</section></section><section id="transforming-data" class="level2" data-number="10.3"><h2 data-number="10.3" class="anchored" data-anchor-id="transforming-data">
<span class="header-section-number">10.3</span> Transforming data</h2>
<section id="subsetting-observations-rows" class="level3" data-number="10.3.1"><h3 data-number="10.3.1" class="anchored" data-anchor-id="subsetting-observations-rows">
<span class="header-section-number">10.3.1</span> Subsetting observations (rows)</h3>
<p>Subsetting observations (rows) is a common data manipulation task in data analysis, allowing us to focus on specific subsets of data that meet particular criteria. This process involves selecting rows from a dataset based on conditions we specify.</p>
<section id="select-observations-by-indexing-position-within" class="level4" data-number="10.3.1.1"><h4 data-number="10.3.1.1" class="anchored" data-anchor-id="select-observations-by-indexing-position-within">
<span class="header-section-number">10.3.1.1</span> <em>Select observations by indexing position within</em> <code>[ ]</code>
</h4>
<p>Just as we use square brackets <code>[row, column]</code> to select elements from matrices, we apply the same approach to select elements from a data frame. For example, by specifying the row indices <code>[5:10, ]</code> within the brackets, we can select the data for rows 5 through 10:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat1</span> <span class="op">&lt;-</span> <span class="va">dat</span><span class="op">[</span><span class="fl">5</span><span class="op">:</span><span class="fl">10</span>, <span class="op">]</span></span>
<span><span class="va">dat1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 5
  patient_id sex      age   sbp heart_rate
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1          5 female    60   123         55
2          6 female    57   121         90
3          7 male      54   120         84
4          8 male      NA   100         92
5          9 female    53   164         72
6         10 male      58   161        102</code></pre>
</div>
</div>
</section><section id="select-observations-by-using-logical-conditions-inside" class="level4" data-number="10.3.1.2"><h4 data-number="10.3.1.2" class="anchored" data-anchor-id="select-observations-by-using-logical-conditions-inside">
<span class="header-section-number">10.3.1.2</span> <em>Select observations by using logical conditions inside</em> <code>[ ]</code>
</h4>
<p>By applying logical conditions, such as greater than (<code>&gt;</code>), less than (<code>&lt;</code>), equal to (<code>==</code>), or combinations of these, we can filter observations that meet specific criteria.</p>
<ul>
<li>For example, we can filter the data to find patients whose age is greater than 55, as follows:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat2</span> <span class="op">&lt;-</span> <span class="va">dat</span><span class="op">[</span><span class="va">dat</span><span class="op">$</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">55</span>, <span class="op">]</span></span>
<span><span class="va">dat2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 13 × 5
   patient_id sex      age   sbp heart_rate
        &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
 1          3 female    58   200        100
 2         NA &lt;NA&gt;      NA    NA         NA
 3          5 female    60   123         55
 4          6 female    57   121         90
 5         NA &lt;NA&gt;      NA    NA         NA
 6         10 male      58   161        102
 7         13 female    57   118         89
 8         17 male      56   126        107
 9         19 male      59   138         85
10         20 male      56   153         85
11         24 female    57   121         90
12         25 male      58   119         87
13         28 male      59    92        119</code></pre>
</div>
</div>
<p><strong>Step-by-step explanation:</strong> First, the code evaluates the expression <code>dat$age &gt; 55</code> for each row in the data frame, generating a logical vector where <code>TRUE</code> indicates patients older than 55 and <code>FALSE</code> indicates others. This logical vector is then used inside the square brackets <code>[ ]</code> to subset the data frame, selecting only the rows where the condition is <code>TRUE</code>. The resulting subset is assigned to the new object <code>dat2</code>. Note that when there are missing values in the <code>age</code> column, the corresponding rows in <code>dat2</code> contain <code>NA</code> values.</p>
<p>Similarly, we can use the <strong><code><a href="https://rdrr.io/r/base/which.html">which()</a></code></strong> function that returns the <strong>indices</strong> where the condition <code>age &gt; 55</code> is <code>TRUE</code>. However, in this case, the missing values are treated as <code>FALSE</code>, resulting in the exclusion of rows where <code>age</code> in the original data is <code>NA</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat3</span> <span class="op">&lt;-</span> <span class="va">dat</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">55</span><span class="op">)</span>, <span class="op">]</span></span>
<span><span class="va">dat3</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 11 × 5
   patient_id sex      age   sbp heart_rate
        &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
 1          3 female    58   200        100
 2          5 female    60   123         55
 3          6 female    57   121         90
 4         10 male      58   161        102
 5         13 female    57   118         89
 6         17 male      56   126        107
 7         19 male      59   138         85
 8         20 male      56   153         85
 9         24 female    57   121         90
10         25 male      58   119         87
11         28 male      59    92        119</code></pre>
</div>
</div>
<ul>
<li>If our objective is to analyze data for female patients aged over 55, we can create a subset by incorporating the logical <strong><code>&amp;</code> operator</strong> to combine the conditions for age and sex.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat4</span> <span class="op">&lt;-</span> <span class="va">dat</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">55</span> <span class="op">&amp;</span> <span class="va">dat</span><span class="op">$</span><span class="va">sex</span> <span class="op">==</span> <span class="st">"female"</span><span class="op">)</span>, <span class="op">]</span></span>
<span><span class="va">dat4</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 5 × 5
  patient_id sex      age   sbp heart_rate
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1          3 female    58   200        100
2          5 female    60   123         55
3          6 female    57   121         90
4         13 female    57   118         89
5         24 female    57   121         90</code></pre>
</div>
</div>
<p>The resulting data frame contains only the rows that meet both of these conditions, namely females over 55 years old.</p>
</section><section id="select-observations-using-the-filter-function-from-dplyr" class="level4" data-number="10.3.1.3"><h4 data-number="10.3.1.3" class="anchored" data-anchor-id="select-observations-using-the-filter-function-from-dplyr">
<span class="header-section-number">10.3.1.3</span> <em>Select observations using the <code>filter()</code> function from <code>dplyr</code></em>
</h4>
<p>The <strong><em>dplyr</em></strong> package also provides the <strong><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code></strong> function for selecting observations.</p>
<ul>
<li>Selecting rows where age is greater than 55:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">dat</span>, <span class="va">age</span> <span class="op">&gt;</span> <span class="fl">55</span><span class="op">)</span></span>
<span><span class="va">dat5</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 11 × 5
   patient_id sex      age   sbp heart_rate
        &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
 1          3 female    58   200        100
 2          5 female    60   123         55
 3          6 female    57   121         90
 4         10 male      58   161        102
 5         13 female    57   118         89
 6         17 male      56   126        107
 7         19 male      59   138         85
 8         20 male      56   153         85
 9         24 female    57   121         90
10         25 male      58   119         87
11         28 male      59    92        119</code></pre>
</div>
</div>
<ul>
<li>Selecting rows where age is greater than 55 and patient is female:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat6</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">dat</span>, <span class="va">age</span> <span class="op">&gt;</span> <span class="fl">55</span> <span class="op">&amp;</span> <span class="va">sex</span> <span class="op">==</span> <span class="st">"female"</span><span class="op">)</span></span>
<span><span class="va">dat6</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 5 × 5
  patient_id sex      age   sbp heart_rate
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1          3 female    58   200        100
2          5 female    60   123         55
3          6 female    57   121         90
4         13 female    57   118         89
5         24 female    57   121         90</code></pre>
</div>
</div>
<p>The above code is equivalent to the following command:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">dat</span>, <span class="va">age</span> <span class="op">&gt;</span> <span class="fl">55</span>, <span class="va">sex</span> <span class="op">==</span> <span class="st">"female"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="content-box-purple">
<p><strong>IMPORTANT</strong></p>
<p>When multiple logical expressions are separated by a comma within the <strong>filter()</strong> function, they are effectively combined using the &amp; operator.</p>
</div>
<p>&nbsp;</p>
</section></section><section id="reordering-observations-rows" class="level3" data-number="10.3.2"><h3 data-number="10.3.2" class="anchored" data-anchor-id="reordering-observations-rows">
<span class="header-section-number">10.3.2</span> Reordering observations (rows)</h3>
<p>Another useful data manipulation involves sorting observations in ascending or descending order of one or more variables (columns). When multiple column names are provided, each additional column helps resolve ties in preceding columns’ values.</p>
<ul>
<li>For example, to arrange the rows of our data based on the values of <code>sbp</code> in ascending order (the default), we can run the following code:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat7</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">dat</span>, <span class="va">sbp</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat7</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 5
  patient_id sex      age   sbp heart_rate
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1         16 male      48    92        122
2         28 male      59    92        119
3          8 male      NA   100         92
4         26 female    48   104         93
5         15 female    50   109        142
6         13 female    57   118         89</code></pre>
</div>
</div>
<ul>
<li>To rearrange the data in descending order based on <code>sbp</code>, we can use the <strong><code><a href="https://dplyr.tidyverse.org/reference/desc.html">desc()</a></code></strong> function within the <strong><em>arrange()</em></strong> function:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat8</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">dat</span>, <span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">sbp</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat8</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 5
  patient_id sex      age   sbp heart_rate
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1         21 male      48   201        104
2          3 female    58   200        100
3          4 male      NA   170         56
4         22 female    52   170         57
5          9 female    53   164         72
6         11 female    49   164         90</code></pre>
</div>
</div>
<p>The above code is equivalent to the following command:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">dat</span>, <span class="op">-</span><span class="va">sbp</span><span class="op">)</span>  <span class="co"># The minus sign indicates descending order</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>We can also sort the data in ascending (or descending) order based first on the values in the column <code>sbp</code> and then on the values in the column <code>heart_rate</code>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat9</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">dat</span>, <span class="va">sbp</span>, <span class="va">heart_rate</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat9</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 5
  patient_id sex      age   sbp heart_rate
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
1         28 male      59    92        119
2         16 male      48    92        122
3          8 male      NA   100         92
4         26 female    48   104         93
5         15 female    50   109        142
6         13 female    57   118         89</code></pre>
</div>
</div>
<p>Notably, two patients (IDs 16 and 28) share the lowest systolic blood pressure of 92 mmHg. When sorting in ascending order, if multiple patients have the same systolic blood pressure, these observations are further sorted by heart rate, with lower heart rate taking precedence. In this case, patient 28, with a heart rate of 119 beats/min, is listed before patient 16, whose heart rate is 122 beats/min.</p>
</section><section id="subsetting-variables-columns" class="level3" data-number="10.3.3"><h3 data-number="10.3.3" class="anchored" data-anchor-id="subsetting-variables-columns">
<span class="header-section-number">10.3.3</span> Subsetting variables (columns)</h3>
<p>When working with data frames, selecting specific variables (columns) for analysis is a common task. For instance, suppose we want to select only the <code>sex</code>, <code>age</code>, and <code>heart_rate</code> variables from the data frame.</p>
<section id="select-variables-by-indexing-their-name-within" class="level4" data-number="10.3.3.1"><h4 data-number="10.3.3.1" class="anchored" data-anchor-id="select-variables-by-indexing-their-name-within">
<span class="header-section-number">10.3.3.1</span> <em>Select variables by indexing their name within</em> <code>[ ]</code>
</h4>
<p>Subsetting variables can be achieved by indexing the variables’ names within <code>[ ]</code>, as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat10</span> <span class="op">&lt;-</span> <span class="va">dat</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sex"</span>, <span class="st">"age"</span> , <span class="st">"heart_rate"</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat10</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 3
  sex      age heart_rate
  &lt;fct&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 male      54         85
2 female    47         84
3 female    58        100
4 male      NA         56
5 female    60         55
6 female    57         90</code></pre>
</div>
</div>
</section><section id="select-variables-by-indexing-position-within" class="level4" data-number="10.3.3.2"><h4 data-number="10.3.3.2" class="anchored" data-anchor-id="select-variables-by-indexing-position-within">
<span class="header-section-number">10.3.3.2</span> <em>Select variables by indexing position within</em> <code>[ ]</code>
</h4>
<p>By specifying the column indices, such as <code>c(2, 3, 5)</code>, within brackets, we can select the data in columns 2, 3, and 5 as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb37" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat11</span> <span class="op">&lt;-</span> <span class="va">dat</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">5</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat11</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 3
  sex      age heart_rate
  &lt;fct&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 male      54         85
2 female    47         84
3 female    58        100
4 male      NA         56
5 female    60         55
6 female    57         90</code></pre>
</div>
</div>
<p>Or we can exclude the variables in the first and forth position.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat12</span> <span class="op">&lt;-</span> <span class="va">dat</span><span class="op">[</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">4</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat12</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 3
  sex      age heart_rate
  &lt;fct&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 male      54         85
2 female    47         84
3 female    58        100
4 male      NA         56
5 female    60         55
6 female    57         90</code></pre>
</div>
</div>
</section><section id="select-variables-using-the-select-function-from-dplyr" class="level4" data-number="10.3.3.3"><h4 data-number="10.3.3.3" class="anchored" data-anchor-id="select-variables-using-the-select-function-from-dplyr">
<span class="header-section-number">10.3.3.3</span> <em>Select variables using the <code>select()</code> function from <code>dplyr</code></em>
</h4>
<p>In <strong><code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code></strong> function we pass the data frame first and then the variables separated by commas. Quotes are optional for column names that don’t contain special characters or spaces.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat13</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">dat</span>, <span class="va">sex</span>, <span class="va">age</span>, <span class="va">heart_rate</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat13</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 3
  sex      age heart_rate
  &lt;fct&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 male      54         85
2 female    47         84
3 female    58        100
4 male      NA         56
5 female    60         55
6 female    57         90</code></pre>
</div>
</div>
<p>Or we can exclude the variables <code>patient_id</code> and <code>sbp</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">dat</span>, <span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">patient_id</span>, <span class="va">sbp</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 30 × 3
   sex      age heart_rate
   &lt;fct&gt;  &lt;dbl&gt;      &lt;dbl&gt;
 1 male      54         85
 2 female    47         84
 3 female    58        100
 4 male      NA         56
 5 female    60         55
 6 female    57         90
 7 male      54         84
 8 male      NA         92
 9 female    53         72
10 male      58        102
# ℹ 20 more rows</code></pre>
</div>
</div>
</section></section><section id="creating-new-variables" class="level3" data-number="10.3.4"><h3 data-number="10.3.4" class="anchored" data-anchor-id="creating-new-variables">
<span class="header-section-number">10.3.4</span> Creating new variables</h3>
<p>Data analysis often involves creating new variables within data frames based on existing variables. This data transformation process involves adding new columns to a data frame derived from the values of one or more existing columns.</p>
<p>Suppose we want to compute a new variable representing the ratio of heart rate to systolic blood pressure (HR/sbp), which we will call <code>shock_index</code>. We can achieve this by using the <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> function from <strong><em>dplyr</em></strong> package, as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat14</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">dat</span>, shock_index <span class="op">=</span> <span class="va">heart_rate</span> <span class="op">/</span> <span class="va">sbp</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat14</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 6
  patient_id sex      age   sbp heart_rate shock_index
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;
1          1 male      54   139         85       0.612
2          2 female    47   151         84       0.556
3          3 female    58   200        100       0.5  
4          4 male      NA   170         56       0.329
5          5 female    60   123         55       0.447
6          6 female    57   121         90       0.744</code></pre>
</div>
</div>
<div class="content-box-purple">
<p><strong>IMPORTANT</strong></p>
<p>By default, the <strong>mutate()</strong> function adds the new variable as the last column in the tibble.</p>
</div>
<p>&nbsp;</p>
<p>Our next step involves categorizing the newly created <code>shock_index</code> variable based on the defined normal range (0.5 to 0.7 beats/mmHg <span class="math inline">\(\cdot\)</span> min). This can be done using the <strong><code><a href="https://dplyr.tidyverse.org/reference/case-and-replace-when.html">case_when()</a></code></strong> function from the <strong><em>dplyr</em></strong> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb47" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat15</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">dat14</span>,</span>
<span>                shock_index1 <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case-and-replace-when.html">case_when</a></span><span class="op">(</span><span class="va">shock_index</span> <span class="op">&lt;</span> <span class="fl">0.5</span> <span class="op">~</span> <span class="st">"low"</span>,</span>
<span>                                         <span class="va">shock_index</span> <span class="op">&lt;=</span> <span class="fl">0.7</span> <span class="op">~</span> <span class="st">"normal"</span>,</span>
<span>                                         <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"high"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">dat15</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 7
  patient_id sex      age   sbp heart_rate shock_index shock_index1
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;       
1          1 male      54   139         85       0.612 normal      
2          2 female    47   151         84       0.556 normal      
3          3 female    58   200        100       0.5   normal      
4          4 male      NA   170         56       0.329 low         
5          5 female    60   123         55       0.447 low         
6          6 female    57   121         90       0.744 high        </code></pre>
</div>
</div>
<p>However, it’s important to keep in mind that transforming continuous variables into categories may simplify interpretation, but it often results in information loss.</p>
</section><section id="using-the-native-pipe-operator-in-a-sequence-of-commands" class="level3" data-number="10.3.5"><h3 data-number="10.3.5" class="anchored" data-anchor-id="using-the-native-pipe-operator-in-a-sequence-of-commands">
<span class="header-section-number">10.3.5</span> Using the native pipe operator in a sequence of commands</h3>
<p>Given that each verb in <strong><em>dplyr</em></strong> specializes in a particular task, addressing complex queries often typically involves integrating several verbs, a process simplified by using the native forward pipe operator, <code>|&gt;</code>.</p>
<p>For example, we want to filter the original dataset to include only rows where the shock index category is “low” or “high”, using a sequence of <strong><em>dplyr</em></strong> verbs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb49" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sub_dat</span> <span class="op">&lt;-</span> <span class="va">dat</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>shock_index <span class="op">=</span> <span class="va">heart_rate</span> <span class="op">/</span> <span class="va">sbp</span>,</span>
<span>         shock_index1 <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case-and-replace-when.html">case_when</a></span><span class="op">(</span><span class="va">shock_index</span> <span class="op">&lt;</span> <span class="fl">0.5</span> <span class="op">~</span> <span class="st">"low"</span>,</span>
<span>                                  <span class="va">shock_index</span> <span class="op">&lt;=</span> <span class="fl">0.7</span> <span class="op">~</span> <span class="st">"normal"</span>,</span>
<span>                                  <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"high"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">shock_index1</span> <span class="op">==</span> <span class="st">"low"</span> <span class="op">|</span> <span class="va">shock_index1</span> <span class="op">==</span> <span class="st">"high"</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We would read this sequence of commands as:</p>
<p><span class="math inline">\(\rightarrow\)</span> Begin with the dataset <code>dat</code>, <strong>then</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Use it as input to the <strong><code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code></strong> function to calculate the <code>shock_index</code> variable and create the <code>shock_index1</code> categorical variable, <strong>then</strong></p>
<p><span class="math inline">\(\rightarrow\)</span> Use this output as input to the <strong><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code></strong> function to select patients with “low” or “high” values of <code>shock index</code>.</p>
<p>The first six rows are shown below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb50" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">sub_dat</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 6 × 7
  patient_id sex      age   sbp heart_rate shock_index shock_index1
       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;       
1          4 male      NA   170         56       0.329 low         
2          5 female    60   123         55       0.447 low         
3          6 female    57   121         90       0.744 high        
4          8 male      NA   100         92       0.92  high        
5          9 female    53   164         72       0.439 low         
6         13 female    57   118         89       0.754 high        </code></pre>
</div>
</div>
<p>Using the <code>%in%</code> operator inside the <strong><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code></strong> function simplifies the code by enabling multiple logical <code>OR</code> conditions to be checked simultaneously.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb52" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>shock_index <span class="op">=</span> <span class="va">heart_rate</span> <span class="op">/</span> <span class="va">sbp</span>,</span>
<span>         shock_index1 <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case-and-replace-when.html">case_when</a></span><span class="op">(</span><span class="va">shock_index</span> <span class="op">&lt;</span> <span class="fl">0.5</span> <span class="op">~</span> <span class="st">"low"</span>,</span>
<span>                                  <span class="va">shock_index</span> <span class="op">&lt;=</span> <span class="fl">0.7</span> <span class="op">~</span> <span class="st">"normal"</span>,</span>
<span>                                  <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"high"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">shock_index1</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"low"</span>, <span class="st">"high"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="content-box-white">
<p><strong>INFO</strong></p>
<p>The native forward pipe operator <span class="math inline">\(|&gt;\)</span> was introduced in base R version 4.1.0. It provides a built-in way to chain function calls in R, similar to the functionality offered by the <span class="math inline">\(&gt;\)</span> operator from the magrittr package.</p>
</div>
<p>&nbsp;</p>
</section></section><section id="summarizing-data" class="level2" data-number="10.4"><h2 data-number="10.4" class="anchored" data-anchor-id="summarizing-data">
<span class="header-section-number">10.4</span> Summarizing data</h2>
<section id="summary-measures" class="level3" data-number="10.4.1"><h3 data-number="10.4.1" class="anchored" data-anchor-id="summary-measures">
<span class="header-section-number">10.4.1</span> Summary measures</h3>
<p>Let’s calculate two common summary measures of the <code>age</code> variable in our data frame: the sample mean and standard deviation. To compute these summary statistics, we use the <strong><code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code></strong> and <strong><code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code></strong> mathematical functions in R (<a href="rcalculator.html" class="quarto-xref"><span>Chapter 3</span></a>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb53" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code>[1] 53.85714</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb55" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">dat</span><span class="op">$</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code>[1] 3.960119</code></pre>
</div>
</div>
<p>Now, we’ll use the <strong><code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code></strong> and <strong><code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code></strong> within the <strong><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code></strong> generic function from the <strong><code>dplyr</code></strong> package. We’ll store the results in a new data frame called <code>stats</code>, which will contain two columns: the <code>mean_age</code> and the <code>sd_age</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb57" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stats</span> <span class="op">&lt;-</span> <span class="va">dat</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mean_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            sd_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">stats</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 1 × 2
  mean_age sd_age
     &lt;dbl&gt;  &lt;dbl&gt;
1     53.9   3.96</code></pre>
</div>
</div>
<div class="content-box-white">
<p><strong>INFO</strong></p>
<p>The <strong>dplyr</strong> package also provides the alternative spelling <strong>summarise()</strong> for users who prefer the UK convention. Both functions work identically.</p>
</div>
<p>&nbsp;</p>
<p>To calculate statistical summaries for multiple columns simultaneously, we can use the <strong><code><a href="https://dplyr.tidyverse.org/reference/across.html">across()</a></code></strong> function within the <strong><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code></strong> function. For example:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb59" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span></span>
<span>    .cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">age</span>, <span class="va">sbp</span><span class="op">)</span>,</span>
<span>    .fns <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>      mean <span class="op">=</span> \<span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">x</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>      sd <span class="op">=</span> \<span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">x</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    .names <span class="op">=</span> <span class="st">"{col}_{fn}"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 1 × 4
  age_mean age_sd sbp_mean sbp_sd
     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
1     53.9   3.96     137.   28.1</code></pre>
</div>
</div>
<p>In the above syntax, the <code>.cols</code> argument specifies the columns to be summarized, while the <code>.fns</code> argument defines the functions to be applied, such as <strong><code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code></strong> and <strong><code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code></strong>, which are wrapped in a list. Finally, the <code>.names</code> argument specifies the naming convention for the output columns. Note that the expressions <code>\(x) mean(x, na.rm = TRUE)</code> and <code>\(x) sd(x, na.rm = TRUE)</code> are examples of “anonymous” functions in R and can also be written using the <em>purrr-style lambda</em> as <code>~ mean(.x, na.rm = TRUE)</code> and <code>~ sd(.x, na.rm = TRUE)</code>, respectively.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb61" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/across.html">across</a></span><span class="op">(</span></span>
<span>    .cols <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">age</span>, <span class="va">sbp</span><span class="op">)</span>,</span>
<span>    .fns <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>      mean <span class="op">=</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">.x</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>      sd <span class="op">=</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">.x</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>,</span>
<span>    .names <span class="op">=</span> <span class="st">"{col}_{fn}"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="content-box-white">
<p><strong>INFO</strong></p>
<p>Anonymous functions, also called lambda functions, are created “on-the-fly” in R without being assigned a name. They are commonly used within other functions or operations, providing a concise and efficient way to perform specific calculations.</p>
</div>
<p>&nbsp;</p>
<p>Next, suppose we want to compute the mean and standard deviation of age for female and male patients <strong>separately</strong>, instead of calculating a single mean and standard deviation for all patients. We can achieve this using the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb62" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculate the mean and sd of age for females and males separately</span></span>
<span><span class="va">stats_by_sex</span> <span class="op">&lt;-</span> <span class="va">dat</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mean_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            sd_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span>   <span class="co"># ungrouping variable is a good habit to prevent errors</span></span>
<span><span class="va">stats_by_sex</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 2 × 3
  sex    mean_age sd_age
  &lt;fct&gt;     &lt;dbl&gt;  &lt;dbl&gt;
1 female     53.2   4.05
2 male       54.8   3.82</code></pre>
</div>
</div>
<p>In this example, the <strong><code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code></strong> function groups the rows of data based on the categories of the <code>sex</code> variable, allowing independent mathematical operations within each group. It is important to note that the <strong><code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code></strong> function itself does not modify the data frame; changes occur only after the <strong><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code></strong> function is applied.</p>
<p>Note that we can simplify the code by using the <code>.by</code> argument of the <strong><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code></strong> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb64" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mean_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            sd_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, .by <span class="op">=</span> <span class="va">sex</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 2 × 3
  sex    mean_age sd_age
  &lt;fct&gt;     &lt;dbl&gt;  &lt;dbl&gt;
1 male       54.8   3.82
2 female     53.2   4.05</code></pre>
</div>
</div>
</section><section id="frequency-statistics" class="level3" data-number="10.4.2"><h3 data-number="10.4.2" class="anchored" data-anchor-id="frequency-statistics">
<span class="header-section-number">10.4.2</span> Frequency Statistics</h3>
<p>Let’s calculate the frequency distribution of the <code>sex</code> variable in our data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb66" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">counts</span> <span class="op">&lt;-</span> <span class="va">dat</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">ungroup</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">counts</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 2 × 2
  sex        n
  &lt;fct&gt;  &lt;int&gt;
1 female    16
2 male      14</code></pre>
</div>
</div>
<p>Here, the <strong><code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code></strong> function is used within the <strong><code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code></strong> function to count the number of rows (observations) within each group defined by the <code>sex</code> variable.</p>
<p>Alternatively, we can use the <strong><code><a href="https://dplyr.tidyverse.org/reference/count.html">count()</a></code></strong> function from the <strong><em>dplyr</em></strong> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb68" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">counts2</span> <span class="op">&lt;-</span> <span class="va">dat</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span></span>
<span><span class="va">counts2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 2 × 2
  sex        n
  &lt;fct&gt;  &lt;int&gt;
1 female    16
2 male      14</code></pre>
</div>
</div>
<p>The main difference is that the <strong><code><a href="https://dplyr.tidyverse.org/reference/count.html">count()</a></code></strong> function automatically handles grouping internally, so there’s no need to explicitly ungroup the data afterward. This simplifies the code and makes it more concise.</p>
</section></section><section id="reshaping-data" class="level2" data-number="10.5"><h2 data-number="10.5" class="anchored" data-anchor-id="reshaping-data">
<span class="header-section-number">10.5</span> Reshaping data</h2>
<p>Reshaping data between “wide” and “long” formats in R is a common task in data transformation. For example, data were collected from four individuals, with total cholesterol (TCH) levels measured at baseline (week 0), as well as at 6 and 12 weeks following a 12-week dietary intervention. The data are stored in an Excel spreadsheet with the following structure:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb70" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat_TCH</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel</a></span><span class="op">(</span><span class="fu"><a href="https://here.r-lib.org/reference/here.html">here</a></span><span class="op">(</span><span class="st">"data"</span>, <span class="st">"cholesterol.xlsx"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat_TCH</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 4 × 3
  week0 week6 week12
  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1  6.42  5.83   5.75
2  6.76  6.2    6.13
3  6.56  5.83   5.71
4  4.8   4.27   4.15</code></pre>
</div>
</div>
<p>We observe that the dataset is organized in what is commonly referred to as a <strong>“wide”</strong> format. This structure is particularly well-suited for a repeated measures design, also known as a longitudinal or within-subject design. In such designs, the same individuals are measured multiple times over a period, with each measurement representing a different time point.</p>
<p>When reshaping data between “wide” and “long” formats, it’s essential to uniquely identify each observation. If no variable in the original data serves this purpose, adding a <strong>row identifier</strong> ensures that each observation retains its identity during the reshaping process, preventing data loss or misalignment. Therefore, before proceeding with data transformation in R, we add a column to the dataset that assigns a unique identifier to each row using the <strong><code><a href="https://tibble.tidyverse.org/reference/rownames.html">rowid_to_column()</a></code></strong> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb72" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat_TCH</span> <span class="op">&lt;-</span> <span class="va">dat_TCH</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tibble.tidyverse.org/reference/rownames.html">rowid_to_column</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">dat_TCH</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 4 × 4
  rowid week0 week6 week12
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1     1  6.42  5.83   5.75
2     2  6.76  6.2    6.13
3     3  6.56  5.83   5.71
4     4  4.8   4.27   4.15</code></pre>
</div>
</div>
<section id="from-wide-to-long-format" class="level3" data-number="10.5.1"><h3 data-number="10.5.1" class="anchored" data-anchor-id="from-wide-to-long-format">
<span class="header-section-number">10.5.1</span> From wide to long format</h3>
<p>The “wide” format may not always be the most suitable data shape for certain types of statistical analyses or visualizations in R, whereas the <strong>“long”</strong> format is often more appropriate. This reshaping process can be achieved using the <strong><code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer()</a></code></strong> function from the <strong><em>dplyr</em></strong> package, as shown below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb74" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat_TCH_long</span> <span class="op">&lt;-</span> <span class="va">dat_TCH</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols <span class="op">=</span> <span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">starts_with</a></span><span class="op">(</span><span class="st">"week"</span><span class="op">)</span>,</span>
<span>               names_to <span class="op">=</span> <span class="st">"week"</span>,</span>
<span>               values_to <span class="op">=</span> <span class="st">"total_cholesterol"</span><span class="op">)</span></span>
<span><span class="va">dat_TCH_long</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 12 × 3
   rowid week   total_cholesterol
   &lt;int&gt; &lt;chr&gt;              &lt;dbl&gt;
 1     1 week0               6.42
 2     1 week6               5.83
 3     1 week12              5.75
 4     2 week0               6.76
 5     2 week6               6.2 
 6     2 week12              6.13
 7     3 week0               6.56
 8     3 week6               5.83
 9     3 week12              5.71
10     4 week0               4.8 
11     4 week6               4.27
12     4 week12              4.15</code></pre>
</div>
</div>
<p>We observe that the “long” format consists of one column for the row ID, one for the week of measurement, and another for the total cholesterol values.</p>
<p>To better understand the dataset transformation from a “wide” to a “long” format, it’s helpful to break down the code and use data from the first two individuals (<a href="#fig-reshape00" class="quarto-xref">Figure&nbsp;<span>10.4</span></a>).</p>
<div id="fig-reshape00" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-reshape00-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reshape00.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reshape00-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.4 Data of the first two participants in the “wide” format.
</figcaption></figure>
</div>
<p>Initially, the <code>cols = starts_with("week")</code> argument specifies which columns from the original data should be pivoted. In this case, it selects the columns that start with the prefix “week”, such as “week0”, “week6”, and “week12”. Additionally, the values in the identifier column (rowid) in the “wide” format are repeated in the “long” format as many times as the number of columns being pivoted, which in this case is three (<a href="#fig-reshape01" class="quarto-xref">Figure&nbsp;<span>10.5</span></a>).</p>
<div id="fig-reshape01" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-reshape01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reshape01.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reshape01-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.5 The values of the identifier column (rowid) of “wide” format are repeated in the “long” format.
</figcaption></figure>
</div>
<p><br></p>
<p>Next, by using the <code>names_to = "week"</code> argument, the column names being pivoted (i.e., week0, week6, and week12) become values within a newly defined variable, <code>week</code>, in the “long” format. These values are repeated as many times as the number of rows in the “wide” format, in this case two, while considering the <code>rowid</code> (<a href="#fig-reshape02" class="quarto-xref">Figure&nbsp;<span>10.6</span></a>).</p>
<div id="fig-reshape02" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-reshape02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reshape02.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reshape02-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.6 The column names being pivoted become values within a newly defined variable in the “long” format.
</figcaption></figure>
</div>
<p><br></p>
<p>Finally, by using the <code>values_to = "total_cholesterol"</code> argument, the cell values from the pivoted variables are placed into a newly defined variable in the “long” format with the name <code>total_cholesterol</code>, with the <code>rowid</code> and <code>week</code> taken into account (<a href="#fig-reshape03" class="quarto-xref">Figure&nbsp;<span>10.7</span></a>).</p>
<div id="fig-reshape03" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-reshape03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reshape03.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reshape03-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.7 The cell values from the pivoted variables are placed into a newly defined variable in the “long” format.
</figcaption></figure>
</div>
<p>&nbsp;</p>
</section><section id="from-long-to-wide-format" class="level3" data-number="10.5.2"><h3 data-number="10.5.2" class="anchored" data-anchor-id="from-long-to-wide-format">
<span class="header-section-number">10.5.2</span> From long to wide format</h3>
<p>The <strong><code><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider()</a></code></strong> function is essentially the reverse of <strong><code><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer()</a></code></strong> function, reshaping data from “long” to “wide” format.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb76" data-source-line-numbers="nil" data-code-line-numbers="nil"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat_TCH_wide</span> <span class="op">&lt;-</span> <span class="va">dat_TCH_long</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider</a></span><span class="op">(</span>id_cols <span class="op">=</span> <span class="va">rowid</span>,</span>
<span>              names_from <span class="op">=</span> <span class="va">week</span>,</span>
<span>              values_from <span class="op">=</span> <span class="va">total_cholesterol</span><span class="op">)</span></span>
<span><span class="va">dat_TCH_wide</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre data-code-line-numbers=""><code># A tibble: 4 × 4
  rowid week0 week6 week12
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1     1  6.42  5.83   5.75
2     2  6.76  6.2    6.13
3     3  6.56  5.83   5.71
4     4  4.8   4.27   4.15</code></pre>
</div>
</div>
<p>To better understand the reshaping process of the <strong><code><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider()</a></code></strong> function, let’s consider the data of the first two individuals in the “long” format (<a href="#fig-reshape000" class="quarto-xref">Figure&nbsp;<span>10.8</span></a>):</p>
<div id="fig-reshape000" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-reshape000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reshape000.png" class="img-fluid figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reshape000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.8 Data of the first two participants in the “long” format.
</figcaption></figure>
</div>
<p>First, in the “wide” format, the <code>rowid</code> column must contain unique values to ensure each row is uniquely identified within the dataset (<a href="#fig-reshape04" class="quarto-xref">Figure&nbsp;<span>10.9</span></a>). This is achieved by using the argument <code>id_cols = rowid</code>, which specifies that the unique values from the <code>rowid</code> column in the “long” format should be used as the identifier column in the “wide” format.</p>
<div id="fig-reshape04" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-reshape04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reshape04.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reshape04-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.9 The rowid values must be unique in the “wide” format.
</figcaption></figure>
</div>
<p><br></p>
<p>Second, the <code>names_from = week</code> argument specifies that the distinct week values in the “long” format serve as the basis for generating new column names (“week0”, “week6”, and “week12”) in the “wide” format (<a href="#fig-reshape05" class="quarto-xref">Figure&nbsp;<span>10.10</span></a>).</p>
<div id="fig-reshape05" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-reshape05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reshape05.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reshape05-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.10 New column names are generated from the distinct week values.
</figcaption></figure>
</div>
<p><br></p>
<p>Finally, the <code>values_from = total_cholesterol</code> argument specifies that the <code>total_cholesterol</code> values of the “long” format must be placed into the cells of the new columns in the “wide” format, considering the rowid and week values (<a href="#fig-reshape06" class="quarto-xref">Figure&nbsp;<span>10.11</span></a>).</p>
<div id="fig-reshape06" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-reshape06-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/reshape06.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reshape06-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca"><strong>FIGURE</strong>&nbsp;10.11 The total cholesterol values are spread across the new columns in the “wide” format.
</figcaption></figure>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-altman2007" class="csl-entry" role="listitem">
Altman, Douglas G, and J Martin Bland. 2007. <span>“Missing Data.”</span> <em>BMJ</em> 334 (7590): 424–24. <a href="https://doi.org/10.1136/bmj.38977.682025.2c">https://doi.org/10.1136/bmj.38977.682025.2c</a>.
</div>
<div id="ref-heymans2022" class="csl-entry" role="listitem">
Heymans, Martijn W., and Jos W. R. Twisk. 2022. <span>“Handling Missing Data in Clinical Research.”</span> <em>Journal of Clinical Epidemiology</em> 151 (November): 185–88. <a href="https://doi.org/10.1016/j.jclinepi.2022.08.016">https://doi.org/10.1016/j.jclinepi.2022.08.016</a>.
</div>
</div>
</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./rlists.html" class="pagination-link" aria-label="Lists and data frames">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Lists and data frames</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./ggplot2.html" class="pagination-link" aria-label="Data visualization with ggplot2">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Data visualization with ggplot2</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2025, Konstantinos I. Bougioukas</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


<script src="site_libs/quarto-contrib/line-highlight-1.0.0/line-highlight.js" defer="true"></script>
</body></html>